import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
    },
    content: {
        height: "auto",
        flexDirection: "row",
        flexWrap: "wrap",
        width: "100%",
        borderColor: "#06c244",
        borderRadius: "10px",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
        borderWidth: 5,
        marginTop: "8px",
    },
    contentA: {
        flex: 1,
        borderColor: "#06c244",
        borderWidth: 5,
        borderRadius: 10,
        elevation: 10,
        padding: "3%",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
        width: "100%",
    },
    title: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#06c244",
        textAlign: "center",
    },
    button: {
        borderRadius: 100,
        maxWidth: "auto",
        minWidth: 90,
        height: 45,
        borderColor: "#06c244",
        borderWidth: 3,
        alignItems: "center",
        justifyContent: "center",
        margin: "2%",
        padding: "3%",
    },
    btn: {
        position: "absolute",
        bottom: "5%",
        right: "5%",
        borderRadius: 30,
        maxWidth: "auto",
        minWidth: 90,
        height: 45,
        borderColor: "#06c244",
        borderWidth: 3,
        alignItems: "center",
        justifyContent: "center",
        margin: "2%",
        padding: "3%",
    },
    titleB: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#06c244",
        textAlign: "left",
    },
});
