import { StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
        paddingHorizontal: 15,
        maxWidth: 700,
    },
    task_content: {
        flex: 1,
        borderColor: "#06c244",
        borderWidth: 0.5,
        borderRadius: 20,
        padding: 20,
        width: "100%",
        alignItems: "flex-start",
        justifyContent: "center",
    },
    content_utils: {
        flex: 0.3,
        minHeight: 10,
        width: "100%"
    },
    content_removed: {
        flex: 0.5,
        width: "100%",
        height: "auto",
        display: "flex",
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'space-evenly',
        borderColor: "#06c244",
        borderRadius: 10,
        borderWidth: 0.5,
        marginTop: 6,
        padding: 10
    },
    content_alts: {
        flex: 2,
        width: "100%",
        display: "flex",
        flexDirection: 'row',
        alignItems: 'flex-end',
        textAlign: 'center',
        borderRadius: 10,
        marginTop: 6,
        padding: 10,
    },
    contentHScroll: {
        flex: 1,
        width: '100%',
        marginTop: 5,
        borderRadius: 5,
        backgroundColor: "#465C46",
    },
    content_text: {
        padding: 20,
        justifyContent: "center",
        flexDirection: "column"
    },
    contentScroll: {
        flex: 1,
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'space-around',
        minWidth: "100%",
    },
    title: {
        fontSize: RFValue(12),
        fontWeight: "bold",
        color: "#06c244",
        textAlign: "center",
    },
    button: {
        borderRadius: 100,
        maxWidth: "auto",
        minWidth: 100,
        height: 'auto',
        minHeight: 50,
        borderColor: "#06c244",
        borderWidth: 1.5,
        alignItems: "center",
        justifyContent: "center",
        margin: 5,
        padding: 8,
    },
    titleA: {
        fontSize: RFValue(13),
        fontFamily: "monospace",
        color: "#06c244",
        textAlign: "left",
        width: 'auto',
        height: "auto",
    },
});